server:
  port: 8082
  forward-headers-strategy: framework

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: auth-service

custom:
  global:
    internalBackUrl: http://localhost:${server.port:8082}
  swagger:
    serverUrl: http://localhost:8080


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: false