server:
  port: 8082
  forward-headers-strategy: framework

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: auth-service
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

custom:
  global:
    internalBackUrl: http://localhost:${server.port:8082}
  swagger:
    serverUrl: http://localhost:8080

service:
  user-service:
    base-url: http://localhost:8081


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: false