server:
  port: 8084
  forward-headers-strategy: framework

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: booking-service

custom:
  global:
    internalBackUrl: http://localhost:${server.port:8084}
  swagger:
    serverUrl: http://localhost:8080

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: false