spring:
  config:
    import: optional:file:.env.dev[.properties]
  datasource:
    url: jdbc:mysql://localhost:3306/ticket_rush
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

services:
  user:
    host: localhost
  auth:
    host: localhost
  performance:
    host: localhost
  booking:
    host: localhost
  payment:
    host: localhost
  seat:
    host: localhost
  ticket:
    host: localhost