custom:
  cors:
    enabled: true
    allowed-origins:
      - http://localhost:8080

services:
  user:
    host: localhost
  auth:
    host: localhost
  performance:
    host: localhost
  booking:
    host: localhost
  payment:
    host: localhost
  seat:
    host: localhost
  ticket:
    host: localhost