spring:
  cloud:
    aws:
      region:
        static: ap-northeast-2
      credentials:
        access-key: dummy
        secret-key: dummy
      stack:
        auto: false
      s3:
        bucket: test-bucket

app:
  event-publisher:
    type: kafka